language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "cp hfa/settings.example.py hfa/settings.py"
  - "pip install -r dependencies.txt"
# command to run tests
script: "./manage.py test hardware users"
